=== ivos/bonds-broker/src/test/java/dataset.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:la="http://lightair.sourceforge.net/">
	<xsd:import namespace="http://lightair.sourceforge.net/" schemaLocation="light-air-types.xsd"/>

	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="bonds" type="bonds__Type"/>
				<xsd:element name="bond_terms" type="bond_terms__Type"/>
				<xsd:element name="ip_address_requests" type="ip_address_requests__Type"/>
				<xsd:element name="flyway_schema_history" type="flyway_schema_history__Type"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="bonds__Type">
		<xsd:attribute name="id" use="optional" type="la:LongType"/>
		<xsd:attribute name="name" use="optional" type="la:StringType"/>
		<xsd:attribute name="start_date" use="optional" type="la:DateType"/>
		<xsd:attribute name="amount" use="optional" type="la:BigdecimalType"/>
		<xsd:attribute name="reference" use="optional" type="la:StringType"/>
	</xsd:complexType>
	<xsd:complexType name="bond_terms__Type">
		<xsd:attribute name="id" use="optional" type="la:LongType"/>
		<xsd:attribute name="bond_id" use="optional" type="la:LongType"/>
		<xsd:attribute name="effective_time" use="optional" type="la:TimestampType"/>
		<xsd:attribute name="end_date" use="optional" type="la:DateType"/>
		<xsd:attribute name="interest_rate" use="optional" type="la:BigdecimalType"/>
	</xsd:complexType>
	<xsd:complexType name="ip_address_requests__Type">
		<xsd:attribute name="id" use="optional" type="la:LongType"/>
		<xsd:attribute name="effective_date" use="optional" type="la:DateType"/>
		<xsd:attribute name="ip" use="optional" type="la:StringType"/>
	</xsd:complexType>
	<xsd:complexType name="flyway_schema_history__Type">
		<xsd:attribute name="installed_rank" use="optional" type="la:IntegerType"/>
		<xsd:attribute name="version" use="optional" type="la:StringNullableType"/>
		<xsd:attribute name="description" use="optional" type="la:StringType"/>
		<xsd:attribute name="type" use="optional" type="la:StringType"/>
		<xsd:attribute name="script" use="optional" type="la:StringType"/>
		<xsd:attribute name="checksum" use="optional" type="la:IntegerNullableType"/>
		<xsd:attribute name="installed_by" use="optional" type="la:StringType"/>
		<xsd:attribute name="installed_on" use="optional" type="la:TimestampType"/>
		<xsd:attribute name="execution_time" use="optional" type="la:IntegerType"/>
		<xsd:attribute name="success" use="optional" type="la:BooleanType"/>
	</xsd:complexType>
</xsd:schema>

=== ivos/bonds-broker/src/test/java/it/bond/buy/bondCountBelowLimit-verify.xml
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../dataset.xsd">

	<ip_address_requests id="@auto" effective_date="@date" ip="127.0.0.1"/>
	<ip_address_requests id="@auto" effective_date="@date" ip="127.0.0.1"/>
	<ip_address_requests id="@auto" effective_date="@date" ip="127.0.0.1"/>
	<ip_address_requests id="@auto" effective_date="@date" ip="127.0.0.1"/>

	<!--created-->
	<bonds id="$bondId" name="name 1" start_date="@date" amount="123" reference="@any"/>
	<bond_terms id="@any" bond_id="$bondId" effective_time="@timestamp" end_date="@date+P5Y" interest_rate="0.05"/>
	<ip_address_requests id="@any" effective_date="@date" ip="127.0.0.1"/>

</dataset>

=== ivos/bonds-broker/src/test/java/it/bond/adjust/extendTerm-verify.xml
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../dataset.xsd">

	<bonds id="1419284901" name="name 1" start_date="2020-02-03" amount="@auto" reference="reference-1"/>
	<bond_terms id="@auto" bond_id="1419284901"/>
	<bond_terms id="@auto" bond_id="1419284901"/>
	<!--last bond term-->
	<bond_terms id="@auto" bond_id="1419284901"/>


	<!--other bond-->
	<bonds id="1419284902"/>
	<!--higher id, but other bond-->
	<bond_terms id="@auto" bond_id="1419284902"/>


	<!--created-->
	<bond_terms id="@any" bond_id="1419284901" effective_time="@timestamp" end_date="2026-02-04" interest_rate="0.045"/>

</dataset>

=== ivos/bonds-broker/src/test/java/it/bond/get/GetBondIT.xml
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../dataset.xsd">

	<!--other-->
	<bonds id="1419284901" name="@auto" start_date="@auto" amount="@auto" reference="@auto"/>
	<bond_terms id="@auto" bond_id="1419284901" effective_time="@auto" end_date="@auto" interest_rate="@auto"/>

	<!--found-->
	<bonds id="1419284902" name="@auto" start_date="@auto" amount="@auto" reference="reference-1"/>
	<bond_terms id="@auto" bond_id="1419284902" effective_time="@auto" end_date="@auto" interest_rate="@auto"/>
	<bond_terms id="@auto" bond_id="1419284902" effective_time="@auto" end_date="@auto" interest_rate="@auto"/>
	<bond_terms id="@auto" bond_id="1419284902" effective_time="@auto" end_date="@auto" interest_rate="@auto"/>

	<!--other-->
	<bonds id="1419284903" name="@auto" start_date="@auto" amount="@auto" reference="@auto"/>
	<bond_terms id="@auto" bond_id="1419284903" effective_time="@auto" end_date="@auto" interest_rate="@auto"/>

</dataset>
